import React from 'react';
import { motion } from 'framer-motion';
import { Sparkles, Heart, Shield, ArrowRight, Stars } from 'lucide-react';

interface LandingPageProps {
  onStart: () => void;
}

const LandingPage: React.FC<LandingPageProps> = ({ onStart }) => {
  return (
    <div className="min-h-screen w-full bg-[#0f172a] text-white overflow-y-auto overflow-x-hidden relative selection:bg-gold-500 selection:text-black">
      {/* Dynamic Background */}
      <div className="fixed inset-0 z-0 pointer-events-none">
        <div className="absolute top-[-10%] right-[-5%] w-[60%] h-[60%] bg-royal-800/30 blur-[120px] rounded-full animate-pulse" />
        <div className="absolute bottom-[-10%] left-[-5%] w-[60%] h-[60%] bg-gold-600/10 blur-[120px] rounded-full" />
      </div>

      {/* Hero Section */}
      <section className="relative z-10 flex flex-col items-center justify-center min-h-[90vh] px-6 text-center">
        <motion.div
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 1, ease: "easeOut" }}
          className="mb-8 relative"
        >
          <div className="absolute inset-0 bg-gold-500 blur-2xl opacity-20 rounded-full" />
          <div className="relative w-24 h-24 bg-gradient-to-br from-royal-900 to-black border border-white/10 rounded-3xl flex items-center justify-center shadow-2xl rotate-3">
             <span className="font-serif italic font-bold text-6xl text-gold-500">V</span>
          </div>
        </motion.div>

        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3, duration: 0.8 }}
          className="font-serif text-5xl md:text-7xl font-bold leading-tight mb-6"
        >
          Love, backed by <br />
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-gold-400 via-gold-200 to-gold-500 italic">
            Intelligence.
          </span>
        </motion.h1>

        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.6 }}
          className="text-slate-300 text-lg max-w-md mx-auto font-light leading-relaxed mb-10"
        >
          Experience a new standard of dating. Deep compatibility insights generated by AI, wrapped in a premium, secure environment.
        </motion.p>

        <motion.button
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.8 }}
          onClick={onStart}
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          className="group relative px-8 py-4 bg-gold-500 text-black font-serif font-bold text-lg rounded-full shadow-[0_0_30px_-5px_rgba(234,179,8,0.4)] overflow-hidden"
        >
          <div className="absolute inset-0 bg-white/20 translate-y-full group-hover:translate-y-0 transition-transform duration-300" />
          <span className="relative flex items-center gap-2">
            Begin Your Journey <ArrowRight className="w-5 h-5" />
          </span>
        </motion.button>
      </section>

      {/* Features Grid */}
      <section className="relative z-10 px-6 pb-20 max-w-lg mx-auto space-y-6">
        <div className="flex items-center gap-4 mb-8 opacity-50">
          <div className="h-[1px] bg-white/20 flex-1" />
          <span className="text-xs uppercase tracking-[0.2em]">Why Vantage</span>
          <div className="h-[1px] bg-white/20 flex-1" />
        </div>

        <FeatureCard 
          icon={<Stars className="w-6 h-6 text-gold-400" />}
          title="AI Compatibility"
          desc="Our algorithms analyze personality depth, not just swipe habits."
          delay={0.2}
        />
        <FeatureCard 
          icon={<Shield className="w-6 h-6 text-purple-400" />}
          title="Verified & Secure"
          desc="Identity verification and secure MoMo payments ensure a safe space."
          delay={0.4}
        />
        <FeatureCard 
          icon={<Heart className="w-6 h-6 text-rose-400" />}
          title="Curated Matches"
          desc="Quality over quantity. We connect you with people who truly resonate."
          delay={0.6}
        />
      </section>

      <footer className="relative z-10 py-8 text-center border-t border-white/5 bg-black/20 backdrop-blur-sm">
        <p className="text-slate-500 text-xs font-serif italic">
          © 2024 Vantage Match. Elevate your standards.
        </p>
      </footer>
    </div>
  );
};

const FeatureCard = ({ icon, title, desc, delay }: any) => (
  <motion.div
    initial={{ opacity: 0, x: -20 }}
    whileInView={{ opacity: 1, x: 0 }}
    viewport={{ once: true }}
    transition={{ delay, duration: 0.6 }}
    className="p-6 rounded-2xl bg-white/5 border border-white/10 backdrop-blur-md flex items-start gap-4 hover:bg-white/10 transition-colors"
  >
    <div className="p-3 rounded-full bg-slate-900 shadow-inner">
      {icon}
    </div>
    <div>
      <h3 className="font-serif font-bold text-xl text-white mb-2">{title}</h3>
      <p className="text-sm text-slate-400 leading-relaxed">
        {desc}
      </p>
    </div>
  </motion.div>
);

export default LandingPage;