import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Smartphone, Lock, CheckCircle, Loader2 } from 'lucide-react';
import { PaymentStatus } from '../types';
import { processMoMoPayment } from '../services/momoService';

interface PaymentModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
}

const PaymentModal: React.FC<PaymentModalProps> = ({ isOpen, onClose, onSuccess }) => {
  const [phoneNumber, setPhoneNumber] = useState('');
  const [status, setStatus] = useState<PaymentStatus>(PaymentStatus.IDLE);
  const [error, setError] = useState<string | null>(null);

  const handlePayment = async () => {
    if (!phoneNumber.match(/^\d{10,12}$/)) {
      setError("Please enter a valid mobile money number.");
      return;
    }

    setStatus(PaymentStatus.PROCESSING);
    setError(null);

    try {
      await processMoMoPayment(phoneNumber, 5000); // 5000 currency units
      setStatus(PaymentStatus.SUCCESS);
      setTimeout(() => {
        onSuccess();
        onClose();
        setStatus(PaymentStatus.IDLE); // Reset for next time
        setPhoneNumber('');
      }, 2000);
    } catch (err: any) {
      setStatus(PaymentStatus.FAILED);
      setError(err.message || "Transaction failed");
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4"
        >
          <motion.div
            initial={{ scale: 0.9, y: 20 }}
            animate={{ scale: 1, y: 0 }}
            exit={{ scale: 0.9, y: 20 }}
            className="w-full max-w-md bg-slate-900 border border-gold-500/30 rounded-2xl p-6 shadow-2xl relative overflow-hidden"
          >
            {/* Background Accent */}
            <div className="absolute -top-10 -right-10 w-40 h-40 bg-gold-500/10 blur-3xl rounded-full pointer-events-none" />

            <button onClick={onClose} className="absolute top-4 right-4 text-slate-400 hover:text-white">
              <X className="w-6 h-6" />
            </button>

            <div className="text-center mb-6">
              <h2 className="text-2xl font-serif font-bold text-white">Unlock Premium</h2>
              <p className="text-slate-400 text-sm mt-2">
                Get unlimited Magic Icebreakers generated by Vantage AI.
              </p>
            </div>

            {status === PaymentStatus.SUCCESS ? (
              <div className="flex flex-col items-center py-8">
                <CheckCircle className="w-16 h-16 text-green-400 mb-4 animate-bounce" />
                <h3 className="text-xl font-bold text-white">Payment Successful!</h3>
                <p className="text-slate-400">Premium features unlocked.</p>
              </div>
            ) : (
              <div className="space-y-4">
                <div className="bg-yellow-500/10 border border-yellow-500/20 p-4 rounded-lg flex items-start gap-3">
                  <div className="p-2 bg-yellow-500/20 rounded-full text-gold-500">
                    <Lock className="w-5 h-5" />
                  </div>
                  <div>
                    <h4 className="font-bold text-gold-400 text-sm">Secure MoMo Payment</h4>
                    <p className="text-xs text-slate-300 mt-1">
                      You will receive a USSD prompt on your phone to approve the transaction of <span className="text-white font-bold">5,000 UGX</span>.
                    </p>
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-bold uppercase text-slate-500 mb-2">
                    Mobile Money Number
                  </label>
                  <div className="relative">
                    <Smartphone className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
                    <input
                      type="tel"
                      value={phoneNumber}
                      onChange={(e) => setPhoneNumber(e.target.value)}
                      placeholder="077..."
                      disabled={status === PaymentStatus.PROCESSING}
                      className="w-full bg-slate-800 border border-slate-700 rounded-lg py-3 pl-10 pr-4 text-white focus:outline-none focus:border-gold-500 transition-colors"
                    />
                  </div>
                  {error && <p className="text-red-400 text-xs mt-2">{error}</p>}
                </div>

                <button
                  onClick={handlePayment}
                  disabled={status === PaymentStatus.PROCESSING || !phoneNumber}
                  className={`w-full py-4 rounded-xl font-bold text-lg flex items-center justify-center gap-2 transition-all ${
                    status === PaymentStatus.PROCESSING
                      ? 'bg-slate-700 text-slate-400 cursor-not-allowed'
                      : 'bg-gradient-to-r from-gold-600 to-gold-500 hover:from-gold-500 hover:to-gold-400 text-black shadow-lg shadow-gold-500/20'
                  }`}
                >
                  {status === PaymentStatus.PROCESSING ? (
                    <>
                      <Loader2 className="w-5 h-5 animate-spin" />
                      Requesting PIN...
                    </>
                  ) : (
                    "Pay Now with MoMo"
                  )}
                </button>
              </div>
            )}
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};

export default PaymentModal;